name: "WORKFLOW.YML"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build for Windows
        run: |
          g++ AnotherFunc.cpp -o AnotherFunc.exe
          g++ SimpleChatter.cpp -o SimpleChatter.exe
          
      - name: Creating out 
        run: | 
          mkdir out 
          copy dist\AnotherFunc.exe out\
          copy dist\SimpleChatter.exe out\ 
      - name: Upload build 
        uses: actions/upload-artifact@master 
        with: 
          name: prog 
          path: out
        
      - name: Upload to Release exe 
        uses: JasonEtco/upload-to-release@v0.1.1 
        env: 
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }} 
        with: 
          args: prog/SimpleChatter.exe application/octet-stream

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "test_git.txt"

      - name: File not exist
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
            echo File does not exist!
            stopMarker=$(uuidgen)
            echo "::stop-commands::$stopMarker"
            echo "::$stopMarker::"
        
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo File exists, ready for !

      - name: DoxygenDocumentationCreate
        uses: mattnotmitt/doxygen-action@edge
        with:
          working-directory: './'
          doxyfile-path: './Doxyfile'
          
      - name: upload result
        uses: actions/upload-artifact@v3
        with:
          path: doc
          name: Doxygen
          
      - name: Push to IO repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './doc'
          destination-github-username: 'UnkoolNobody'
          destination-repository-name: 'SimpleChatter.io'
          user-email: 'michaelzh2002@mail.ru'
          commit-message: 'Doxygen-documentation'
          target-branch: main
