name: "File existence check"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "test_git.txt"

      - name: File not exist
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
            echo File does not exist!
            stopMarker=$(uuidgen)
            echo "::stop-commands::$stopMarker"
            echo "::$stopMarker::"
        
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo File exists, ready for !
        
      - uses: actions/checkout@v2 
      - name: DoxygenDocumentationCreate
        uses: mattnotmitt/doxygen-action@v1.9.3
        with:
          doxyfile-path: './Doxyfile'
      - name: upload result
        uses: actions/upload-artifact@v3
        with:
          path: doc
          name: Doxygen
      - name: Push to IO repository
        uses: cpina/github-action-rush-to-another-repository@main
        env:
          KEY: ${{ secrets.KEY }}
        with:
          source-directory: 'doc'
          destination-github-username: 'UnkoolNobody'
          destination-repository-name: 'SimpleChatter.io'
          user-email: 'michaelzh2002@mail.ru'
          commit-massage: 'Doxygen-documentation'
          target-branch: main
