name: "File existence check"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "test_git.txt"

      - name: File not exist
         run: |
          if: steps.check_files.outputs.files_exists == 'false'
         run: echo File does not exist!
          stopMarker=$(uuidgen)
          echo "::stop-commands::$stopMarker"
          echo "::$stopMarker::"
        
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo File exists, ready for !
